version: '3.8'

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./server:/app
      - /Users/geeth/Pictures/photoaura:/var/aura/data  # Adding a named volume for data persistence
    depends_on:
      - postgres  # Ensure the backend waits for PostgreSQL to be ready
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000  # or any other command to start your FastAPI backend
    env_file:
      - .env.local

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: pnpm run dev  # or any other command to start your Next.js frontend
    env_file:
      - .env.local


networks:
  app-network:
    driver: bridge

volumes:
  aura-data:
    driver: local
  postgres-data:
    driver: local
    