version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./server:/app
      - /Volumes/share-data/photoaura:/var/aura/data  # Adding a named volume for data persistence
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000  # or any other command to start your FastAPI backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: pnpm run dev  # or any other command to start your Next.js frontend


networks:
  app-network:
    driver: bridge

volumes:
  aura-data:
    driver: local
