version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./server:/app
      - /mnt/share-data/photoaura:/var/aura/data  # Adding a named volume for data persistence
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000  # or any other command to start your FastAPI backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - /app/client/node_modules # Consider only mounting node_modules or specific directories if necessary
    networks:
      - app-network
    command: pnpm run start  # or any other command to start your Next.js frontend
      
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  aura-data:
    driver: local
