version: '3.8'

services:
  photoaura-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"  # Expose the frontend on port 80
      - "8000:8000"  # Expose the backend on port 8000 directly if needed
    volumes:
      - /mnt/share-data/photoaura:/var/aura/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
