version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./server:/app
      - /mnt/share-data/photoaura:/var/aura/data
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Mount custom Nginx config directory
    ports:
      - "80:82"  # Map external port 80 to internal port 82
      - "443:445"  # Map external port 443 to internal port 445, if you're setting up HTTPS
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  aura-data:
    driver: local
