name: Deploy to App Server

on:
  push:
    branches:
      - master
    paths:
      - 'server/**'
      - 'docker-compose*.yml'
      - 'Dockerfile*'
      - '.env'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /home/geeth/apps/photoaura
            git pull origin main
            docker compose -f docker-compose-backend.yml build --no-cache
            docker compose -f docker-compose-backend.yml up -d
          EOF